# Generated by Django 5.2.10 on 2026-02-03 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="ФИО Врача"),
                ),
                (
                    "specialization",
                    models.CharField(max_length=100, verbose_name="Специализация"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
            ],
            options={
                "verbose_name": "Врач",
                "verbose_name_plural": "Врачи",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Кличка")),
                (
                    "species",
                    models.CharField(max_length=50, verbose_name="Вид животного"),
                ),
                (
                    "breed",
                    models.CharField(blank=True, max_length=100, verbose_name="Порода"),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(max_length=150, verbose_name="ФИО Владельца"),
                ),
                (
                    "owner_phone",
                    models.CharField(max_length=20, verbose_name="Телефон владельца"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Пациент",
                "verbose_name_plural": "Пациенты",
            },
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis", models.CharField(max_length=200, verbose_name="Диагноз")),
                ("treatment", models.TextField(verbose_name="Назначенное лечение")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата осмотра"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clinic.doctor",
                        verbose_name="Врач",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="clinic.patient",
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись в медкарте",
                "verbose_name_plural": "Медицинские карты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(verbose_name="Дата и время приема")),
                ("complaint", models.TextField(blank=True, verbose_name="Жалоба")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Запланировано"),
                            ("completed", "Завершено"),
                            ("canceled", "Отменено"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinic.doctor",
                        verbose_name="Врач",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinic.patient",
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись на прием",
                "verbose_name_plural": "Записи на прием",
                "ordering": ["-date_time"],
            },
        ),
    ]
