# Generated by Django 5.2.10 on 2026-02-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="telegram_id",
            field=models.CharField(
                blank=True,
                help_text="Узнать свой ID можно у бота @userinfobot",
                max_length=20,
                null=True,
            ),
        ),
    ]
