# Generated by Django 5.2.11 on 2026-02-04 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0002_doctor_telegram_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="diagnosis",
            field=models.TextField(blank=True, default="", verbose_name="Диагноз"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="prescription",
            field=models.TextField(
                blank=True, default="", verbose_name="Назначения / Рецепт"
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="clinic.patient",
                verbose_name="Пациент",
            ),
        ),
        migrations.DeleteModel(
            name="MedicalRecord",
        ),
    ]
